// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const config = require('../config');

const { rootUrl, localAdmin: { email, password }, e2e: { drivers } } = config;

drivers.forEach(driverName =>
{
  describe('Authentication', function() 
  {
    this.timeout(30000)
    let driver

    beforeEach(async function() 
    {
      driver = await new Builder().forBrowser(driverName).build()
    });

    afterEach(async function() 
    {
      await driver.quit();
    });

    it('lets you login', async function() 
    {
      await driver.get(rootUrl);
      await driver.findElement(By.linkText("Login")).click();
      await driver.findElement(By.name("email")).sendKeys(email);
      await driver.findElement(By.name("email")).sendKeys(Key.ENTER);
      await driver.findElement(By.name("password")).sendKeys(password);
      await driver.findElement(By.name("password")).sendKeys(Key.ENTER);
      await driver.wait(until.elementTextContains(driver.findElement(By.css('.navbar-brand')), 'Welcome John Doe'), 1000);
    });
  });
});

