// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver';
import config from '../config';

const { rootUrl, localAdmin: { email, password }, e2e: { drivers } } = config;

drivers.forEach(driverName =>
{
  describe('Authentication', function()
  {
    this.timeout(30000);
    let driver;

    beforeEach(async () =>
    {
      driver = await new Builder().forBrowser(driverName).build();
    });

    afterEach(async () =>
    {
      await driver.quit();
    });

    it('lets you login', async () =>
    {
      await driver.get(rootUrl);
      await driver.findElement(By.linkText("Login")).click();
      await driver.findElement(By.name("email")).sendKeys(email);
      await driver.findElement(By.name("email")).sendKeys(Key.ENTER);
      await driver.findElement(By.name("password")).sendKeys(password);
      await driver.findElement(By.name("password")).sendKeys(Key.ENTER);
      await driver.findElement(By.css('.navbar-brand'), 'Welcome John Doe');
    });
  });
});

